name: Package standalone artifacts and build
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: install dependencies
      run: sudo apt install gcc-arm-none-eabi qemu-system
    - name: Package standalone artificats
      run: |
        make -j$(nproc) standalone
    - name: Make sure all standalone artifacts build
      run: |
        for standalone in standalone/*; do make -C $standalone; done